unique_ids:
  assets:
    standard-page.html: VXMTZZSKKB2QY5BAX3GBVJKMFETSBZ67
    theme.css: TCTUVSCSQKAH2PRRFR3Q7SWBNRFYWXMF
  forms:
    Form1: QA6E3PC5VLNXEZCWA55ZEGUFN3KG2NHM
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: V7UYD3N7LZEBO2G75NLRR2Q6EL4LEF76
